version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POCKETBASE_URL=http://localhost:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - pocketbase

  pocketbase:
    build: ../database
    ports:
      - "8080:8080"
    volumes:
      - pb_data:/app/pb_data
      - ./pb_hooks:/app/pb_hooks:rw
      - ./pb_public:/app/pb_public:rw
    restart: unless-stopped

volumes:
  pb_data:
    driver: local 